// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Models.Data;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(LibDbContext))]
    [Migration("20231207001337_baza2")]
    partial class baza2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApplication4.Models.Book.BookEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorFullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BookCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("b2c0a923-fee6-468b-a1fa-3ae5a563460a"),
                            AuthorFullname = "Dr. Akula",
                            BookCount = 5,
                            CategoryId = new Guid("2b64b94c-ab89-49cb-8a6c-2fd7f577b510"),
                            CreatedOn = new DateTime(2023, 12, 7, 1, 13, 35, 617, DateTimeKind.Local).AddTicks(2144),
                            Isbn = "7685948576945",
                            PageCount = 300,
                            PublishDate = new DateTime(2007, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Drakoola"
                        },
                        new
                        {
                            BookId = new Guid("b06036c4-5320-4263-926d-86b537a32386"),
                            AuthorFullname = "Król Edward",
                            BookCount = 0,
                            CategoryId = new Guid("ee8d72c8-13b0-4d49-8a97-4d9e62920fa4"),
                            CreatedOn = new DateTime(2023, 12, 7, 1, 13, 34, 617, DateTimeKind.Local).AddTicks(2239),
                            Isbn = "7685948556945",
                            PageCount = 200,
                            PublishDate = new DateTime(2009, 9, 9, 1, 1, 1, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Im The Best"
                        },
                        new
                        {
                            BookId = new Guid("7c4ab0d3-9fee-4b22-bce3-419b2607ce10"),
                            AuthorFullname = "Dog",
                            BookCount = 7,
                            CategoryId = new Guid("88c25e8f-70b6-46fc-9f94-7bfbcb671bd3"),
                            CreatedOn = new DateTime(2023, 12, 7, 1, 13, 33, 617, DateTimeKind.Local).AddTicks(2267),
                            Isbn = "7615948576945",
                            PageCount = 235,
                            PublishDate = new DateTime(2015, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Dog vs Human"
                        },
                        new
                        {
                            BookId = new Guid("7860e1fa-d69c-4471-909d-575895caa888"),
                            AuthorFullname = "Iaman Alien",
                            BookCount = 5,
                            CategoryId = new Guid("2b64b94c-ab89-49cb-8a6c-2fd7f577b510"),
                            CreatedOn = new DateTime(2023, 12, 7, 1, 13, 32, 617, DateTimeKind.Local).AddTicks(2291),
                            Isbn = "4685948576945",
                            PageCount = 300,
                            PublishDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Aliens"
                        },
                        new
                        {
                            BookId = new Guid("fa846053-4113-4e50-93c4-d91fa64fb845"),
                            AuthorFullname = "Adolfo Hilter",
                            BookCount = 2,
                            CategoryId = new Guid("dde93c20-6ff3-448c-ba62-90ee8c235cfd"),
                            CreatedOn = new DateTime(2023, 12, 7, 1, 13, 36, 617, DateTimeKind.Local).AddTicks(2315),
                            Isbn = "7685948576945",
                            PageCount = 1200,
                            PublishDate = new DateTime(1949, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "A Very Argentine Mustachy Artist"
                        },
                        new
                        {
                            BookId = new Guid("583c89ce-688c-4fec-8846-dcc2a62be7b4"),
                            AuthorFullname = "Nota Duck, PH.D.",
                            BookCount = 1,
                            CategoryId = new Guid("a9e344f0-9275-43c9-a2d2-06c30c47e318"),
                            CreatedOn = new DateTime(2023, 12, 7, 1, 13, 31, 617, DateTimeKind.Local).AddTicks(2341),
                            Isbn = "7777777777777",
                            PageCount = 50000,
                            PublishDate = new DateTime(2007, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Title = "Quack Quack"
                        });
                });

            modelBuilder.Entity("WebApplication4.Models.Cart.RentEntity", b =>
                {
                    b.Property<Guid>("RentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RentId");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("WebApplication4.Models.Category.CategoryEntity", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("a953284c-6f77-4d2f-a7bb-88d66a705006"),
                            Name = "Kryminalna"
                        },
                        new
                        {
                            CategoryId = new Guid("0e3e02b1-a767-49ae-bc81-3d68ef98e8b9"),
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = new Guid("2cb154d4-0275-470c-8907-4cbcee29ec92"),
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            CategoryId = new Guid("70023a37-4ac7-4bb7-a966-6b838b0f2a60"),
                            Name = "Romans"
                        },
                        new
                        {
                            CategoryId = new Guid("210bfd87-4651-4257-96ab-2877e5052d21"),
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("WebApplication4.Models.User.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5bf1cf7c-e156-4696-81fc-4fed8e19e710",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ce77752-d761-4ac9-9a1a-89cf8aa1bc91",
                            Email = "damian@wp.pl",
                            EmailConfirmed = true,
                            FirstName = "Damian",
                            LastName = "Maksimowicz",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAMIAN@WP.PL",
                            NormalizedUserName = "DAMIAN@WP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAENfSx9ZQt3QkTNMTvqdMpQgSj9Q4E7TFboRrC5y+INf/Wc4cDuw8rVtE//M0WBNFUA==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "6fbcafd7-1581-41d2-9eed-8bc935a907bf",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "damian@wp.pl"
                        },
                        new
                        {
                            Id = "a41d6452-3896-4c04-93d2-3ec249e69895",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae333be3-31f8-456f-9bd0-22f8fefffa57",
                            Email = "gosc@wp.pl",
                            EmailConfirmed = true,
                            FirstName = "Gosc",
                            LastName = "Gosc",
                            LockoutEnabled = false,
                            NormalizedEmail = "GOSC@WP.PL",
                            NormalizedUserName = "GOSC@WP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEIg5HnxzCuJPPWrrcqOIX0wpJmoh5tqEkC5or2vNhBja1z7XZt7Tm556nBqNuJ7v4w==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "3f08053e-8666-46c7-bdc7-612a323c16f5",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "gosc@wp.pl"
                        },
                        new
                        {
                            Id = "46c16260-3e9a-490e-b1fa-b9adc40a482c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43e7ebb2-7ee9-44a9-ac6c-28a0e8a04da2",
                            Email = "pracownik@wp.pl",
                            EmailConfirmed = true,
                            FirstName = "Pracownik",
                            LastName = "Pracownik",
                            LockoutEnabled = false,
                            NormalizedEmail = "PRACOWNIK@WP.PL",
                            NormalizedUserName = "PRACOWNIK@WP.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEPX7R8R4Emv6/oUY/g7NXRKavJOeV1Hu50lHX3mlnEYu9/Wg8MIwLisIF3BFqxYDYw==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "23ea01cd-38ec-4505-be64-74942786da89",
                            Status = 1,
                            TwoFactorEnabled = false,
                            UserName = "pracownik@wp.pl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApplication4.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApplication4.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication4.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApplication4.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication4.Models.Book.BookEntity", b =>
                {
                    b.HasOne("WebApplication4.Models.Category.CategoryEntity", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApplication4.Models.Cart.RentEntity", b =>
                {
                    b.HasOne("WebApplication4.Models.Book.BookEntity", "bBook")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication4.Models.User.AppUser", "bUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("bBook");

                    b.Navigation("bUser");
                });

            modelBuilder.Entity("WebApplication4.Models.Category.CategoryEntity", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
